apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-sets
  namespace: argocd
  labels:
    repository: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/infralight/product-projects.git
    path: argocd/application-sets
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: {}