apiVersion: batch/v1
kind: CronJob
metadata:
  name: total-assets
  labels:
    app: total-assets
    environment: production
spec:
  schedule: {{ .Values.schedule }}
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: total-assets-deployment
            image: {{ .Values.image }}
            envFrom:
              - secretRef:
                  name: total-assets-secrets
          restartPolicy: Never
