serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::094724549126:role/product-aws-load-balancer-controller-irsa"
terminationGracePeriodSeconds: 120
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512M
clusterName: "product"
region: "us-east-1"
defaultTargetType: "ip"
podDisruptionBudget:
  maxUnavailable: 1
# serviceMonitor:
#   enabled: true
